[project]
name = "lumberjack"
version = "0.1.0"
description = "Testbench dependencies for the lumberjack accelerator"
readme = "README.md"
requires-python = ">=3.12"

dependencies = [
    "cocotb>=2.0",
    "pytest>=8.4.2",
    "numpy",
    "ml_dtypes",
    "pyyaml>=6.0.3",
    "ruamel-yaml>=0.19.1",
]

[dependency-groups]
dev = [
    "ruff>=0.15.21",
]
