[project]
name = "lumberjack"
version = "0.1.0"
authors = ["Justin Beaurivage <code@beaurivage.io>"]

[dependencies]
memutils = { version = "0.4.0", git = "https://github.com/jbeaurivage/memutils-veryl.git" }
# memutils = { version = "0.4.0", path = "../memutils-veryl" }

[build]
clock_type = "posedge"
reset_type = "async_low"

sources = ["src", "tb", "benchmark"]
target = { type = "directory", path = "target/veryl" }

[format]
vertical_align = true

[test]
waveform_target = { type = "directory", path = "target/waveform" }
waveform_format = "fst"
include_files = [
    "tb/utils.py",
    "tb/wb_driver.py",
    "tb/test_forest.py",
    "tb/test_cases.py",
    "tb/test_data/tree_2n_aligned.hex",
    "tb/test_data/tree_2n_misaligned.hex",
    "tb/test_data/tree_2n_circular.hex",
    "tb/test_data/forest_1c_2t_6n_aligned.hex",
    "tb/test_data/forest_2c_2t_6n_aligned.hex",
    "tb/test_data/forest_1c_2t_6n_misaligned.hex",
    "tb/test_data/forest_2c_2t_6n_misaligned.hex",
    "tb/test_data/forest_1c_2t_6n_circular.hex",
    "tb/test_data/forest_2c_2t_6n_circular.hex",
]