[project]
name = "lumberjack"
version = "0.1.0"
authors = ["Justin Beaurivage <code@beaurivage.io>"]

[dependencies]
memutils = { version = "0.3.0", git = "https://github.com/jbeaurivage/memutils-veryl.git" }
# memutils = { version = "0.3.0", path = "../memutils-veryl" }

[build]
clock_type = "posedge"
reset_type = "async_low"

sources = ["src"]
target = { type = "directory", path = "target/veryl" }

[test]
waveform_target = { type = "directory", path = "target/waveform" }
waveform_format = "fst"
include_files = [
    "tb/utils.py",
    "tb/test_data/single_tree_2_nodes.hex",
    "tb/test_data/forest_2_trees_6_nodes.hex",
]